 hosts: vmcreate
  gather_facts: false
  connection: local
  vars:
    vcenter_hostname: 192.168.0.4
    esxhost: 192.168.0.4
    datastore: NFS001
    network: VLAN001
    vmtemplate: CentOS7
    vmcluster: AppsDev
    notes: Created by Ansible
  tasks:
    - name: Check for regular variables
      fail: msg="Must pass name to -e"
      when: name is not defined

    - name: Check vSphere access parameters
      fatal: msg="Must set vcenter_user and vcenter_pass in a Vault"
      when: (vcenter_user is not defined) or (vcenter_pass is not defined)

    - name: Create VM from template
      vsphere_guest:
        vcenter_hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_user }}"
        password: "{{ name }}"
        from_template: yes
        template_src: "{{ vmtemplate }}"
        cluster: "{{ vmcluster }}"
        resource_pool: "/Resources"
        vm_extra_config:
          notes: "{{ notes }}"
